apiVersion: apps/v1
kind: Deployment
metadata:
    name: bookingconfirmation-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: bookingconfirmation
    template:
        metadata:
            labels:
                app: bookingconfirmation
        spec:
            containers:
                - name: bookingconfirmation
                  image: ionipatro/bookingconfirmation:latest